version: '3'
services:
    php:
        build:
            context: ./docker
            dockerfile: php.${PHPBUILD}.Dockerfile
        volumes:
            - './nginx/html:/var/www/html'
    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        healthcheck:
            test: [ "CMD", "nc", "-vz", "-w1", "localhost", "80" ]
            interval: 1s
            timeout: 1s
            retries: 30
        links:
            - 'php'
        volumes:
            - './nginx/html:/var/www/html'
