version: '3'
services:
    php:
        build:
            context: ./docker
            dockerfile: php.7.4.33.Dockerfile
        volumes:
            - './app:/var/www/html'
    nginx:
        image: nginx:latest
        links:
            - 'php'
        volumes:
            - './app:/var/www/html'
            - './nginx/nginx.conf/:/etc/nginx/nginx.conf'
            - './nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf'
