version: '3'
services:
    php:
        build:
            context: ./docker
            dockerfile: php.${PHPBUILD}.Dockerfile
        volumes:
            - './app:/var/www/html'
    nginx:
        image: nginx:latest
        ports:
            - '80'
            - '443'
        links:
            - 'php'
        volumes:
            - './app:/var/www/html'
            - './nginx/nginx.conf/:/etc/nginx/'
            - './nginx/conf.d/default.conf:/etc/nginx/conf.d/'
