version: '3'
services:
    php:
        build:
            context: ./docker
            dockerfile: php.${PHPBUILD}.Dockerfile
        volumes:
            - './nginx/html/:/var/www/html/'
    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        ports:
            - "80"
            - "443"
        links:
            - 'php'
        volumes:
            - './nginx/html/:/var/www/html/'
