version: '3'
services:
    php:
        build:
            context: ./docker
            dockerfile: php.${PHPBUILD}.Dockerfile
        volumes:
            - './app:/var/www/html'
    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        links:
            - 'php'
        volumes:
            - './nginx/app/:/var/www/html'
