version: '3'
services:
    php:
        build:
            context: ./docker
            dockerfile: php.${PHPBUILD}.Dockerfile

    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        links:
            - 'php'
